# Task 33: Neural Networks Basics:

#### Neural Networks:
<br>
A neural network is a connected network (where nodes are interconnected and there are several layers) which takes an input value and compute the desired output.

#### Components of a Neural Network:
A typical neural network comprises of the following components

- Input Layer.
- Hidden Layer (where the computations and calculations will be happening).
- Output Layer.
- Weights & Bias (associated with the input values.
- Activation Function.
- Loss Function.

***Layers:*** Layers are used to hold the neurons and pass it on to the subsequent layers. Each neuron is a mathematical operation that takes its input multiplies it by the weight associated with it and then passes the sum through the activation functions to the other neurons. Types of layers are
- Input layer
- Hidden layer
- Output layer

***Weights and Bias:*** Weights are chosen at random in the beginning and optimized during training to reduce the loss. Bias it's simply a constant value that is added to the weights sum of inputs to offset the result.

***Activation Function:*** An activation function is basically normalizing the computed input to produce an output. There can be various activation functions like sigmoid function, linear function, softmax and relu function.

In [1]:
# import library
import numpy as np

### Assign input values:

In [3]:
inp_value = np.array([[0,0],[0,1],[1,1],[1,0]])
inp_value.shape
inp_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

### Assign output values:

In [4]:
output = np.array([0,1,1,0])
output = output.reshape(4,1)
output.shape

(4, 1)

### Assign weights:

In [6]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

### Add bias:

In [7]:
bias = 0.3

### Activation Function:

In [9]:
def sigmoid_func(x):
    return 1/(1 + np.exp(-x))

### Derivative of Sigmoid Function:

In [11]:
def der(x):
    return sigmoid_func(x) * (1 - sigmoid_func(x))

### Updating Weights:

In [12]:
for epochs in range(10000):
    inp_arr = inp_value
    
    weighted_sum = np.dot(inp_arr, weights) + bias
    first_output = sigmoid_func(weighted_sum)
    
    error = first_output - output
    total_error = np.square(np.subtract(first_output,output)).mean()
    #print(total_error)
    
    first_der = error
    second_der = der(first_output)
    derivative = first_der * second_der
    
    t_input = inp_value.T # transpose the input values
    final_derivative = np.dot(t_input,derivative)
    
    # update weights
    weights = weights - 0.05 * final_derivative
    
    # update bias
    for i in derivative:
        bias = bias - 0.05 * i

print("Updated weights:\n", weights)
print("\nUpdated Bias:", bias)

Updated weights:
 [[-0.41953547]
 [ 8.98887811]]

Updated Bias: [-4.19706344]


So now to get the prediction done we will check it for the new value.

### Predictions:

In [13]:
pred = np.array([0,1])

result = np.dot(pred, weights) + bias

res = sigmoid_func(result)

print("Predicted Result:", res)

Predicted Result: [0.99177089]


So for [0,1] the target output is 1. Our result is basically 0.9917 so it's pretty accurate. This is how you can implement **Neural Networks** in python.