# Task 21: Linear Algebra & Calculus Using NumPy

### Importing Libraries:

In [8]:
import numpy as np
from scipy.linalg import lu, qr
from scipy.optimize import minimize

## Linear Algebra Tasks:

NumPy provides us with functions for performing common linear algebra tasks, such as array multiplication, solving linear systems, and more.

### 1. Matrix Creation and Manipulation:

In [2]:
# creating 3x3 zero matrix
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

# creating 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:\n", identity_matrix)

# creating 3x3 random matrix
random_matrix = np.random.randint(0, 10, (3,3))
print("\nRandom Matrix:\n", random_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Matrix:
 [[4 4 9]
 [0 3 1]
 [8 9 8]]


- **np.eye()** in Python returns a 2-D array with 1's as the diagonal and 0's elsewhere.

In [3]:
# addition of identity matrix and random matrix
add_result = identity_matrix + random_matrix
print("Identity Matrix + Random Matrix\n", add_result)

Identity Matrix + Random Matrix
 [[5. 4. 9.]
 [0. 4. 1.]
 [8. 9. 9.]]


In [4]:
# subtraction of identity matrix and random matrix
sub_result = random_matrix - identity_matrix
print("Random Matrix - Identity Matrix\n", sub_result)

Random Matrix - Identity Matrix
 [[3. 4. 9.]
 [0. 2. 1.]
 [8. 9. 7.]]


In [5]:
# dot product of the two matrices
mul_result = identity_matrix * sub_result
print("Identity Matrix x Subtracted Result Matrix\n", mul_result)

Identity Matrix x Subtracted Result Matrix
 [[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 7.]]


In [6]:
# tranpose of a identity matrix
transpose = np.transpose(random_matrix)
print("Transpose of a Identity Matrix:\n", transpose)

Transpose of a Identity Matrix:
 [[4 0 8]
 [4 3 9]
 [9 1 8]]


In [7]:
# determinant of random matrix
det = np.linalg.det(random_matrix)
print("Determinant of Random Matrix:\n", det)

Determinant of Random Matrix:
 -123.99999999999991


In [8]:
# inverse of random matrix
if np.linalg.det(random_matrix) != 0:  # check if the matrix is invertible
    inverse_matrix = np.linalg.inv(random_matrix)
    print("Inverse of Random Matrix:\n", inverse_matrix)
else:
    print("Random Matrix is not invertible.")

Inverse of Random Matrix:
 [[-0.12096774 -0.39516129  0.18548387]
 [-0.06451613  0.32258065  0.03225806]
 [ 0.19354839  0.03225806 -0.09677419]]


- **np.linalg.inv()**   calculates the inverse of a matrix.
- **np.linalg.det()**	calculates the determinant of a matrix.
- **np.transpose()**	transposes a matrix

### 2. Solving Linear Equations:

##### Solving system of linear equation:

In [9]:
# example system: 2x + 3y = 5, 4x + 6y = 10
A = np.array([[2, 3], [4, 6]])
b = np.array([5, 10])

# check if the system has unique solution
if np.linalg.det(A) != 0:
    x = np.linalg.solve(A, b)
    print("Solution to the system of equations:\n", x)
else:
    print("The system does not have a unique solution.")

The system does not have a unique solution.


In [24]:
# example system: 3x + 9y = 5, 2x + 10y = 10
A2 = np.array([[3, 9], [2, 10]])
b2 = np.array([5, 10])

# check if the system has unique solution
if np.linalg.det(A2) != 0:
    x2 = np.linalg.solve(A2, b2)
    print("Solution to the system of equations:\n", x2)
else:
    print("The system does not have a unique solution.")

Solution to the system of equations:
 [-3.33333333  1.66666667]


##### LU Decomposition:

In [10]:
# considering random matrix
P, L, U = lu(random_matrix)

print("LU Decomposition:")
print("P Matrix:\n", P)
print("L Matrix:\n", L)
print("U Matrix:\n", U)

LU Decomposition:
P Matrix:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L Matrix:
 [[ 1.          0.          0.        ]
 [ 0.          1.          0.        ]
 [ 0.5        -0.16666667  1.        ]]
U Matrix:
 [[8.         9.         8.        ]
 [0.         3.         1.        ]
 [0.         0.         5.16666667]]


##### QR Decomposition:

In [11]:
# considering random matrix
Q, R = qr(random_matrix)

print("QR Decomposition:")
print("Q Matrix:\n", Q)
print("R Matrix:\n", R)

QR Decomposition:
Q Matrix:
 [[-0.4472136   0.13187609 -0.88465174]
 [-0.         -0.98907071 -0.14744196]
 [-0.89442719 -0.06593805  0.44232587]]
R Matrix:
 [[ -8.94427191  -9.8386991  -11.18033989]
 [  0.          -3.03315018  -0.32969024]
 [  0.           0.          -4.57070064]]


### 3. Eigenvalues and Eigenvectors:

##### Calculate the eigenvalues and eigenvectors of a given matrix.

In [12]:
# considering random matrix
eigenvalues, eigenvectors = np.linalg.eig(random_matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [15.32023857 -3.00959413  2.68935557]
Eigenvectors:
 [[-0.63454929 -0.76095902  0.65953591]
 [-0.06252712 -0.10649636 -0.71783507]
 [-0.77034899  0.63999992  0.22299147]]


In [13]:
# verify by reconstructing the original matrix

D = np.diag(eigenvalues)
P = eigenvectors
P_inv = np.linalg.inv(P)
A_reconstructed = P @ D @ P_inv
print("\nReconstructed Matrix:\n", A_reconstructed)


Reconstructed Matrix:
 [[ 4.00000000e+00  4.00000000e+00  9.00000000e+00]
 [-1.22124533e-15  3.00000000e+00  1.00000000e+00]
 [ 8.00000000e+00  9.00000000e+00  8.00000000e+00]]


- A = PDP^(-1), where D is a diagonal matrix of eigenvalues and P is a matrix of eigenvectors.

### 4. Vector Operations:

In [29]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

# addition of vectors
addition = v1 + v2
print("Addition Result:\n", addition)

# dot product of vectors
dot_product = np.dot(v1, v2)
print("\nDot Product Result:\n", dot_product)

# cross product of vectors
cross_product= np.cross(v1, v2)
print("\nCross Product Result:\n", cross_product)

Addition Result:
 [5 7 9]

Dot Product Result:
 32

Cross Product Result:
 [-3  6 -3]


##### Normalize a vector:

In [30]:
norm_v1 = np.linalg.norm(v1)
normalized_v1 = v1 / norm_v1
print("Normalized Vector v1:\n", normalized_v1)

Normalized Vector v1:
 [0.26726124 0.53452248 0.80178373]


##### Compute vector norms:

- L1 Norm of a vector is also known as the Manhattan distance or Taxicab norm.
- L2 norm of a vector is Euclidean distance.
- L-infinity norm (also known as the maximum norm or Chebyshev norm).

In [31]:
l2_norm = np.linalg.norm(v1)
l1_norm = np.linalg.norm(v1, ord=1)
inf_norm = np.linalg.norm(v1, ord=np.inf)

print("L2 Norm of v1:\n", l2_norm)
print("\nL1 Norm of v1:\n", l1_norm)
print("\nInfinity Norm of v1:\n", inf_norm)

L2 Norm of v1:
 3.7416573867739413

L1 Norm of v1:
 6.0

Infinity Norm of v1:
 3.0


The default value for ord is 2, so if it's not specified, **np.linalg.norm** calculates the L2 norm by default.
<br>
Vector norm is calculated as:
- L1 norm=∣v1∣+∣v2∣+∣v3∣
- L-infinity norm=max(∣v1∣,∣v2∣,∣v3∣)
- L2 norm= sqrt(v1^2+v2^2+v3^2)

### 5. Matrix Decomposition:

In [15]:
# considering random matrix
meaned_mat = random_matrix - np.mean(random_matrix, axis=0)
meaned_mat

array([[ 0.        , -1.33333333,  3.        ],
       [-4.        , -2.33333333, -5.        ],
       [ 4.        ,  3.66666667,  2.        ]])

- Standardize the data (mean centering). Subtract the mean of each feature from the data to center it around the origin.

In [16]:
# compute the covariance matrix
cov_matrix = np.cov(meaned_mat, rowvar=False)
cov_matrix

array([[16.        , 12.        , 14.        ],
       [12.        , 10.33333333,  7.5       ],
       [14.        ,  7.5       , 19.        ]])

##### Perform Singular Value Decomposition (SVD):

In [17]:
U, S, Vt = np.linalg.svd(cov_matrix)

In [21]:
# project the data onto the principal components
rand_mat_pca = np.dot(meaned_mat, Vt.T)

- I use Vt.T because Vt is the transpose of V.

In [22]:
print("Original Data:\n", random_matrix)
print("\nMean Centered Data:\n", meaned_mat)
print("\nCovariance Matrix:\n", cov_matrix)
print("\nU (left singular vectors):\n", U)
print("\nS (singular values):\n", S)
print("\nVt (right singular vectors, transposed):\n", Vt)
print("\nProjected Data (PCA):\n", rand_mat_pca)

Original Data:
 [[4 4 9]
 [0 3 1]
 [8 9 8]]

Mean Centered Data:
 [[ 0.         -1.33333333  3.        ]
 [-4.         -2.33333333 -5.        ]
 [ 4.          3.66666667  2.        ]]

Covariance Matrix:
 [[16.         12.         14.        ]
 [12.         10.33333333  7.5       ]
 [14.          7.5        19.        ]]

U (left singular vectors):
 [[-0.63541713 -0.2762147  -0.72107594]
 [-0.44238977 -0.63515764  0.63313985]
 [-0.63287942  0.72130453  0.28139549]]

S (singular values):
 [3.82987206e+01 7.03461270e+00 1.23310416e-15]

Vt (right singular vectors, transposed):
 [[-0.63541713 -0.44238977 -0.63287942]
 [-0.2762147  -0.63515764  0.72130453]
 [-0.72107594  0.63313985  0.28139549]]

Projected Data (PCA):
 [[-1.30878523e+00  3.01079043e+00  0.00000000e+00]
 [ 6.73830842e+00 -1.01962936e+00 -4.44089210e-16]
 [-5.42952319e+00 -1.99116106e+00  8.88178420e-16]]


## Calculus Tasks:

NumPy, a powerful numerical library in Python, provides tools to perform basic calculus operations such as differentiation and integration numerically. NumPy allows for efficient and practical numerical computation of derivatives and integrals, which are essential for various applications in science and engineering.

### 1. Numerical Integration:

Numerical integration can be performed using techniques like the Trapezoidal rule or Simpson's rule.

In [23]:
def trapezoidal_rule(f, a, b, n):
    
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h/2) * (y[0] + 2*np.sum(y[1:-1]) + y[-1])
    return integral

# cheching
f = lambda x: x**2
a = 0
b = 1
n = 100
result = trapezoidal_rule(f, a, b, n)
print("Trapezoidal rule result:", result)

Trapezoidal rule result: 0.33335000000000004


In [25]:
def simpsons_rule(f, a, b, n):
    if n % 2 == 1:
        raise ValueError("n must be an even number.")
    
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    integral = (h/3) * (y[0] + 4*np.sum(y[1:-1:2]) + 2*np.sum(y[2:-2:2]) + y[-1])
    return integral

# checking
f = lambda x: x**2
a = 0
b = 1
n = 50
result = simpsons_rule(f, a, b, n)
print("Simpson's rule result:", result)

Simpson's rule result: 0.33333333333333337


**Note**: 'n' must be an even number (for simpson's rule)
- 'f' is the function to integrate.
- 'a' and 'b' are the start and end points of the interval.
- 'n' is the number of intervals.

### 2. Numerical Differenciation:

Implementations of numerical differentiation using forward, backward, and central difference methods with NumPy.

In [3]:
# forward difference method
def forward_difference(f, x, h):
    return (f(x + h) - f(x)) / h

# to check
f = lambda x: x**2
x = 1
h = 0.01
result_fd = forward_difference(f, x, h)
print("Forward difference result:", result_fd)

Forward difference result: 2.0100000000000007


The forward difference method approximates the derivative by using the difference between the function value at a point and the function value at the next point.
- f : The function to differentiate.
- x : The point at which to compute the derivative.
- h : The step size.

In [4]:
# backward difference method
def backward_difference(f, x, h):
    return (f(x) - f(x - h)) / h

# checking
f = lambda x: x**2
x = 1
h = 0.01
result_bd = backward_difference(f, x, h)
print("Backward difference result:", result_bd)

Backward difference result: 1.9900000000000029


The backward difference method approximates the derivative by using the difference between the function value at a point and the function value at the previous point.
- f : The function to differentiate.
- x : The point at which to compute the derivative.
- h : The step size.

In [5]:
# central difference method
def central_difference(f, x, h):
    return (f(x + h) - f(x - h)) / (2 * h)

# checking
f = lambda x: x**2
x = 1
h = 0.01
result_cd = central_difference(f, x, h)
print("Central difference result:", result_cd)

Central difference result: 2.0000000000000018


The central difference method approximates the derivative by using the difference between the function values at the next and previous points.
- f : The function to differentiate.
- x : The point at which to compute the derivative.
- h : The step size.

### 3. Partial Derivatives:

Let's consider a function f(x,y) = x^2 + y^2. We will compute the partial derivatives with respect to x and y.

In [6]:
def partial_derivative(f, var_index, point, h=1e-5):
    
    point_forward = np.array(point, dtype=float)
    point_backward = np.array(point, dtype=float)
    
    point_forward[var_index] += h
    point_backward[var_index] -= h
    
    return (f(*point_forward) - f(*point_backward)) / (2 * h)

# example func.
f = lambda x, y: x**2 + y**2

# point at which to compute the partial derivatives
point = (1, 1)

# compute partial derivatives
partial_x = partial_derivative(f, 0, point)
partial_y = partial_derivative(f, 1, point)

print("Partial derivative with respect to x:", partial_x)
print("Partial derivative with respect to y:", partial_y)

Partial derivative with respect to x: 2.000000000002
Partial derivative with respect to y: 2.000000000002


- **'f'** is the multivariable function to differentiate.
- **'var_index'** is the index of the variable with respect to which to compute the partial derivative.
- **'point'** is the point at which to compute the partial derivative.
- **'h'** is the step size, defaulting to 1e-5.

In [7]:
# analytical solutions for verification
analy_partial_x = 2 * point[0]
analy_partial_y = 2 * point[1]

print("Analytical partial derivative with respect to x:", analy_partial_x)
print("Analytical partial derivative with respect to y:", analy_partial_y)

# verifying
assert np.isclose(partial_x, analy_partial_x, atol=1e-5), "Partial derivative with respect to x is incorrect."
assert np.isclose(partial_y, analy_partial_y, atol=1e-5), "Partial derivative with respect to y is incorrect."

print("Results verified and are correct.")

Analytical partial derivative with respect to x: 2
Analytical partial derivative with respect to y: 2
Results verified and are correct.


**np.isclose(partial_x, analytical_partial_x, atol=1e-5)**:
- This function checks if the partial derivative of x is approximately equals to the analytical solution of x.
- atol=1e-5 specifies the absolute tolerance. This means the difference between partial_x and analytical_partial_x must be within 10^-5.

**assert**:

- This keyword is used to perform the check.
- If np.isclose(partial_x, analytical_partial_x, atol=1e-5) returns True, the program continues execution.
- If returns False, assert statement raises an AssertionError and stops the program, indicating that the numerical result does not match the analytical result within the specified tolerance.

### 4. Optimization:

Let's minimize the function f(x,y) = (x-1)^2 + (y-2)^2 subject to the constraint x+y ≤ 3.

In [9]:
def objective_function(x):
    return (x[0] - 1)**2 + (x[1] - 2)**2

def constraint(x):
    return 3 - (x[0] + x[1])

# initial guess
x0 = np.array([0.5, 0.5])

# constraint in the form of a dictionary
cons = {'type': 'ineq', 'fun': constraint}

# perform the optimization
res_opt = minimize(objective_function, x0, constraints=cons)

print("Optimal value of x:", res_opt.x)
print("Optimal objective function value:", res_opt.fun)

Optimal value of x: [0.99999999 1.99999999]
Optimal objective function value: 2.4984835742366904e-16


- **Constraints Definition**: The constraints are defined in a dictionary format with 'type': 'ineq' indicating it's an inequality constraint and 'fun': constraint specifying the constraint function.