# Task 11: NumPy Advanced Operations

## Indexing and Slicing:

In [1]:
# import NumPy library
import numpy as np

#### Extract a 3x3 sub-array from a 2D array of size 5x5.

In [11]:
array_2d = np.random.randint(10, 51, size=(5, 5))

# print the 2D array
print("2D Array (5x5) with random no. b/w 10 and 50:")
print(array_2d)

# extracting 3x3 sub-array
print("\n3x3 Sub-array is:")
print(array_2d[1:4, 1:4])

2D Array (5x5) with random no. b/w 10 and 50:
[[21 39 39 10 48]
 [23 34 44 35 23]
 [34 44 18 33 18]
 [14 24 17 23 14]
 [43 35 43 43 41]]

3x3 Sub-array is:
[[34 44 35]
 [44 18 33]
 [24 17 23]]


#### From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis.

In [4]:
array_3d = np.array([[[ 1,  2], [ 3,  4], [ 5,  6]],
                     [[ 7,  8], [ 9, 10], [11, 12]],
                     [[13, 14], [15, 16], [17, 18]],
                     [[19, 20], [21, 22], [23, 24]]])

# extract all elements in the first two rows and all columns of the second slice along the third axis
ext_slice = array_3d[:2, :, 1]

print("3D Array:\n", array_3d)
print("\nExtracted Elements (first two rows, second slice):\n", ext_slice)

3D Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]

Extracted Elements (first two rows, second slice):
 [[ 2  4  6]
 [ 8 10 12]]


#### Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7].

In [5]:
# define an array
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# use fancy indexing to extract elements at positions [1, 3, 4, 7]
indices = [1, 3, 4, 7]
extracted_elements = array[indices]

print("Array: ", array)
print("Extracted Elements at positions [1, 3, 4, 7]:", extracted_elements)

Array:  [ 10  20  30  40  50  60  70  80  90 100]
Extracted Elements at positions [1, 3, 4, 7]: [20 40 50 80]


#### Given a 2D array, use fancy indexing to select rows [0, 2, 3] and columns [1, 3].

In [12]:
# Use fancy indexing to select rows [0, 2, 3] and columns [1, 3]
rows = [0, 2, 3]
cols = [1, 3]

# use numpy.ix_ to create a meshgrid for fancy indexing
# considering 2D array that already been defined
selected_elements = array_2d[np.ix_(rows, cols)]

print("2D Array:\n", array_2d)
print("\nSelected Elements (rows [0, 2, 3] and columns [1, 3]):\n", selected_elements)

2D Array:
 [[21 39 39 10 48]
 [23 34 44 35 23]
 [34 44 18 33 18]
 [14 24 17 23 14]
 [43 35 43 43 41]]

Selected Elements (rows [0, 2, 3] and columns [1, 3]):
 [[39 10]
 [44 33]
 [24 23]]


**np.ix_ Function:** This function creates a meshgrid-like selection for the specified rows and columns. It returns a tuple of arrays that can be used to index the 2D array, effectively selecting a sub-array formed by the intersection of the specified rows and columns.

#### Extract all elements that are greater than 10 from a 1D array of random integers.

In [8]:
# create a 1D array of random integers b/w 0 and 20, with size of 15
array_1d = np.random.randint(0, 21, size=15)

# extract all elements that are greater than 10
elmnts_grtr_thn_10 = array_1d[array_1d > 10]

print("1D Array:", array_1d)
print("\nElements Greater Than 10:", elmnts_grtr_thn_10)

1D Array: [15  4 13  1  5  6  2  3  0  3 18  4 20  9 18]

Elements Greater Than 10: [15 13 18 20 18]


#### Given a 2D array of shape (5, 5), replace all elements greater than 15 with the value 0.

In [13]:
#considering 2D array from above question
print("2D Array:\n", array_2d)

# replace all elements greater than 15 with the value 0
array_2d[array_2d > 15] = 0

print("\nModified Array (elements > 15 replaced with 0):\n", array_2d)

2D Array:
 [[21 39 39 10 48]
 [23 34 44 35 23]
 [34 44 18 33 18]
 [14 24 17 23 14]
 [43 35 43 43 41]]

Modified Array (elements > 15 replaced with 0):
 [[ 0  0  0 10  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [14  0  0  0 14]
 [ 0  0  0  0  0]]


## Broadcasting:

**Broadcasting** is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes without explicitly reshaping or replicating data. This feature simplifies code and can significantly improve performance by avoiding unnecessary memory usage.

#### Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).

In [9]:
# define 1D array of shape (3,)
arr_1d = np.array([1, 2, 3])

# define 2D array of shape (4, 3)
arr_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90],
                     [100, 110, 120]])

# add 1D array to each row of the 2D array
rslt = arr_2d + arr_1d

print("1D Array:\n", array_1d)
print("\n2D Array:\n", array_2d)
print("\nResult after adding 1D array to each row of 2D array:\n", rslt)

1D Array:
 [15  0 19  7  7  1  1 13  2  6  4 16 15  2 18]

2D Array:
 [[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0 10 15  0]
 [10  0 11  0  0]
 [ 0  0  0  0  0]]

Result after adding 1D array to each row of 2D array:
 [[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


#### Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).

In [10]:
# define a 2D array of shape (3, 3)
array_2d_multiply = np.array([[2, 4, 6],
                              [1, 3, 5],
                              [7, 8, 9]])

# considering 1D array of shape (3,) as shown above
# multiplying
result = array_2d_multiply * arr_1d

print("2D Array for Multiplication:\n", array_2d_multiply)
print("1D Array for Multiplication:\n", arr_1d)
print("\nResult after multiplication:\n", result)

2D Array for Multiplication:
 [[2 4 6]
 [1 3 5]
 [7 8 9]]
1D Array for Multiplication:
 [1 2 3]

Result after multiplication:
 [[ 2  8 18]
 [ 1  6 15]
 [ 7 16 27]]


#### Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.

In [11]:
# define a 2D array of shape (3, 1)
ary2d_1 = np.array([[1],
                    [2],
                    [3]])

# define a 2D array of shape (1, 4)
ary2d_2 = np.array([[10, 20, 30, 40]])

# perform element-wise addition
re_sult = ary2d_1 + ary2d_2

print("2D Array of shape (3, 1):\n", ary2d_1)
print("\n2D Array of shape (1, 4):\n", ary2d_2)
print("\nResult after element-wise addition:\n", re_sult)

2D Array of shape (3, 1):
 [[1]
 [2]
 [3]]

2D Array of shape (1, 4):
 [[10 20 30 40]]

Result after element-wise addition:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


#### Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.

In [12]:
# define 3D array of shape (2, 3, 4)
aray_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# define 2D array of shape (3, 4)
aray_2d_add = np.array([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

# add the 2D array to each 2D slice along the first axis
resu_lt = aray_3d + aray_2d_add

print("3D Array of shape (2, 3, 4):\n", aray_3d)
print("\n2D Array to be added:\n", aray_2d_add)
print("\nResult after adding 2D array to each 2D slice along the first axis:\n", resu_lt)

3D Array of shape (2, 3, 4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

2D Array to be added:
 [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]

Result after adding 2D array to each 2D slice along the first axis:
 [[[ 2  3  4  5]
  [ 7  8  9 10]
  [12 13 14 15]]

 [[14 15 16 17]
  [19 20 21 22]
  [24 25 26 27]]]


## Some other questions:

#### Extract diagonal elements from a 2D array.

In [14]:
def ext_diag_elements(a_2d):
    
    # convert input to numpy array if it's not already
    a_2d = np.array(a_2d)
    
    # extract the diagonal elements
    diag_elemnts = np.diag(a_2d)
    
    # convert the diagonal elements to a list
    return diag_elemnts.tolist()

# eg
a_2d = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

diag_elemnts = ext_diag_elements(a_2d)
print("Diagonal Elements: ", diag_elemnts)

Diagonal Elements:  [1, 5, 9]


#### Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.

In [16]:
def extract_every_second(arrray_2d):
    
    # convert input to numpy array if it is not already
    arrray_2d = np.array(arrray_2d)
    
    # use slicing to extract every second row and every second column, starting from index 1
    sliced_array = arrray_2d[1::2, 1::2]
    
    return sliced_array

# eg
arrray_2d = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

resul_t = extract_every_second(arrray_2d)
print("This is required row & column: \n", resul_t)

This is required row & column: 
 [[ 6  8]
 [14 16]]


#### Use slicing to reverse the order of elements in each row of a 2D array.

In [22]:
# considering array from the above question

def reverse_rows(arrray_2d):
    
    # convert input to numpy array if it is not already
    arrray_2d = np.array(arrray_2d)
    
    # reverse the order of elements in each row using slicing
    reversed_array = arrray_2d[:, ::-1]
    
    return reversed_array

arrray_2d = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

rsltt = reverse_rows(arrray_2d)
print("Reversed array is: \n", rsltt)

Reversed array is: 
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


#### Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [26]:
# considering 2D array from the second question of this section 

def set_last_col(arrray_2d):
    
    # convert input to a numpy array if it's not already
    arrray_2d = np.array(arrray_2d)
    
    # calculate the sum of the first two columns
    sum_two_col = arrray_2d[:, 0] + arrray_2d[:, 1]
    
    # set the last column to the sum of the first two columns using broadcasting
    arrray_2d[:, -1] = sum_two_col
    
    return arrray_2d


ans = set_last_col(arrray_2d)
print("New Array: \n", ans)

New Array: 
 [[ 1  2  3  3]
 [ 5  6  7 11]
 [ 9 10 11 19]
 [13 14 15 27]]
